# lightning.pytorch==2.5.1.post0
seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
  - class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: scratch_w2v2/fold0
      save_dir: .
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: vmc24_mos
      log_model: false
      experiment: null
      prefix: ''
      checkpoint_name: null
      entity: null
      notes: null
      tags: null
      config: null
      config_exclude_keys: null
      config_include_keys: null
      allow_val_change: null
      group: scratch_w2v2
      job_type: null
      mode: null
      force: null
      reinit: null
      resume: null
      resume_from: null
      fork_from: null
      save_code: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      settings: null
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: '{epoch:02d}-{val_loss:.2f}'
      monitor: val/loss
      verbose: false
      save_last: null
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 24
  gradient_clip_val: 1.0
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  model_registry: null
model:
  ssl_model_path: facebook/wav2vec2-base
  pretrained_model_path: null
data:
  train_mos_data_path: /work/gj18/e43001/github.com/sfi-utmos/notebooks/train_0_7fold.csv
  valid_mos_data_path: /work/gj18/e43001/github.com/sfi-utmos/notebooks/val_0_7fold.csv
  wav_root: /work/gj18/e43001/mos_corpus/vmc24/track3_obf/DATA/wav
  batch_size: 1
  shuffle: true
optimizer: null
lr_scheduler: null
ckpt_path: null
